### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by sangwonl** [sangwonl/qnsqnd#8]
```
panic: send on closed channel

goroutine 24 [running]:
github.com/sangwonl/qnsqnd/pkg/core.(*Subscription).processDelivery(0xc00024e050, 0xc001456be0)
	~/qnsqnd/pkg/core/dispatchers.go:37 +0x8a
github.com/sangwonl/qnsqnd/pkg/core.(*Subscription).subscriptionQueueDispatcher(0xc00024e050)
	~/qnsqnd/pkg/core/dispatchers.go:45 +0x32
created by github.com/sangwonl/qnsqnd/pkg/core.(*TopicMsgInbox).addSubscription
	~/qnsqnd/pkg/core/inbox.go:19 +0xfc
```

**Comment by sangwonl** [comment]
good read:
https://go101.org/article/channel-closing.html
